language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    -secure: L9dMMVrZ9wFX2oC+VlSCS9hJyOlwkk6JTvc2zqJP8nabmm2eQU1Ou6lgcE26+/ly4GstymjdpTnPDRlhwe5JlyqHAaOQHG0rwCKttQbVrOhq6tJkJbaaZCtGGHgv6FZSd6w+FzIZ44mVEXmi9Dd9JYXZ0SCTBt3O9yy6pAE+N7MZQQPISecmaX4V5FbDfNgAeNcpgZbNl4YQSzrxUrWcIP3rHjQjwuRW/d1slcmiAEo6IyA07KZ1qFbb657vis2wJDYMVxHoYXDE+KzRp2lsNg7tplhMdWzWTvJEfUmSaezDuYRWV8slrieAlcKi0y6Ha/ktF3plv/oLx+uVoN/m5T+DSev3rtdk8Kh13smd9zhIBtVALj9+kca/SfGMMaE7KRrXC7z58pLZcJx2ZsoFBu2r8zyTWHTuO1yDzO0mWsc4LebXWi1w5zhfCssl9P+wTiWyKlnbJbDa9qGO8Qo2fro22bCK1HOIZYgI5QAAxz+l5iphg9WmrRr0MK9DthJywkhhOzini7D7n3mgkJ1WfnnNjgNSXqB1qT5Sd+cjK4b5pXJiVVL8XktHecCajQTwvIfqP1yj8xk9NMe0/6fAbayqFLJCDWg/wZibEkXrt2yM2NKzf8dssRkRtjIKez8xJ4Wwiz9qAmFkOXEjzpSTUJubXBp3jTEG1MyWXDDIa28=
    # FIREBASE_SECRET
    -secure: B3Db0LgoP/s7cHJzKWbPPMkI0YbSym7NC7UMe7Ddg3Z7CdTBpqgRXT5fmAnAUd++C0rq5Wqr7zLONgRpaMr6DFtG+7mZR8FWUlGJIEmNAjGXPzLZDicw8heo09835wf/45jDRjvSnGhK8+ihplVawxbMjjn3ohC6l8CJYls8Z6/ord6IVWDae0xIevRBHYiN2dUG6p1eRj4D0NRBDegKgoVXksnrLP32Bu993xmR+auoP7aWqDTmtfD8PhW4WW/KcZtDj1CaO+/RxSdd0xgc44hgvRM8T1YCQf9DnmkHVitBbQjSydWrfot4GkSrxFXnGMuOla30TxgfqUk1aMrYhgF9IcvE87E04HK0yi3lZRLC+xbhPkvDYl8Elbn8tPWwO8Ucu5U/EwYozJLJbrLwlwWpsr+cWUDH8+W1zJR1ePCeNklh5A4wLErW1GcJ2y1NChu3141NkrGRcd//Rq5Ia+aZuWXY4ZTNcy/wLxgHVGH94RnvhqqR+vx96f1p27uBB11hmtXq38+J2dVwbKQD1LQSB0wNpZw1N5+jdgix3IoLmTyRisyWL4cMuDuKFQ0O21aU4+E6iYWf4/xAo2y3EaMKOcuNo51w3XgoJsoYxh5iE+BA2h2WIJOThuokmf5XHeOl9xtGeLoBctL52yEumTyNiwEZ/bZZXrwxsk7uTrA=
